docs: add post 2024-12-18

diff --git a/auto-push b/auto-push
--- a/auto-push
+++ b/auto-push
@@ -1,4 +1,13 @@
 #!/usr/bin/env bash
+php bin/archive.php > docs/t/index.md
+
+if [ $? -eq 0 ]; then
+    echo "Archive success"
+else
+    echo "Archive failed"
+    exit 1
+fi
+
 git add *
 git add .gitignore
 git commit -m "docs: add post `date "+%Y-%m-%d"`"
